# Numpy

## Arrays

<p>Numpy arrays are fixed-type contiguous collections with high flexibility and efficiency in indexing methods and operations. There are several data types that can be used for arrays, the most common are:</p>
<ul>
<li><em>int8, int16, int32, int64</em></li>
<li><em>uint8, uint16, uint32, uint64</em></li>
<li><em>float16, float16, float64</em></li>
<li><em>complex64, complex128</em></li>
<li><em>bool</em></li>
</ul>
<p><strong>Multidimensiona arrays</strong></p>
<p>Each array is characterized by a set of&nbsp;<strong>axes&nbsp;</strong>and a&nbsp;<strong>shape</strong>. The axes of an array define its dimensions:</p>
<ul>
<li>a row vectos has 1 axis</li>
<li>a 2D matrix has 2 axes</li>
<li>a ND array has N axes</li>
</ul>
<p><img src="./img/n2.png" alt="" width="348" height="100" /></p>
<p>Axes can be numbered with negative values, the axis with index -1 is always along the <strong>row</strong>, while the last dimension added always take the lowest value (with sign) both with positive and negative indexing.</p>
<p>The <strong>shape</strong> of an array is a tuple that specifies the number of elements along each axis. a column vector is a 2D matrix.</p>
<p><img src="./img/n3.png" alt="" width="348" height="100" /></p>
<p><img src="./img/n4.png" alt="" width="348" height="100" /></p>

In [2]:
import numpy as np

matrix = [[1, 2, 3], 
          [4, 5, 6], 
          [7, 8, 9]]

np.array(matrix, dtype=np.uint8)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=uint8)

In [15]:
null_matrix = np.zeros((2, 3), dtype=np.int8)
id_matrix = np.ones((2, 3), dtype=np.int8)
full_matrix = np.full((3, 3), 10, dtype=np.int8)

print(null_matrix, end='\n\n')
print(id_matrix, end='\n\n')
print(full_matrix, end='\n\n')

[[0 0 0]
 [0 0 0]]

[[1 1 1]
 [1 1 1]]

[[10 10 10]
 [10 10 10]
 [10 10 10]]



In [22]:
#10 sample in range 0-1
linear = np.linspace(0, 1, 10)

#Sequence 10-20 with step 2
step_2 = np.arange(10, 21, 2)

#Random (2,3) matrix with normal distribution µ=5 std=2
gauss_matrix = np.random.normal(5, 2, (2,3)) 

#Random (3,4) matrix with uniform distribution on [0,1]
uniform_matrix = np.random.random((3, 4))

print(linear, end='\n\n')
print(step_2, end='\n\n')
print(gauss_matrix, end='\n\n')
print(uniform_matrix, end='\n\n')

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

[10 12 14 16 18 20]

[[6.85297424 3.45181087 4.60646984]
 [2.79465194 6.17277103 4.63421926]]

[[0.30015284 0.24675824 0.65499347 0.65107258]
 [0.91260191 0.19759293 0.35468297 0.46651739]
 [0.36234707 0.69808161 0.75283637 0.19247025]]



In [26]:
x = np.array([[2, 3, 4], [8, 6, 7]])
dimensions = x.ndim 
matrix_shape = x.shape
matrix_size = x.size

print(dimensions, matrix_shape, matrix_size)

2 (2, 3) 6


## Computation on Numpy

<p><strong>Universal Functions (element-wise)</strong></p>
<ul>
<li><strong>Binary</strong> operations with arrays of the <strong>same shape</strong><br />
<ul>
<li>sum &amp; subtraction (+ -)</li>
<li>multiplication &amp; division (* /)</li>
<li>modulus (%)</li>
<li>floor division (//)</li>
<li>exponentiation (**)</li>
<p><img src="./img/n5.png" alt="" width="450" height="100" /></p>
</ul>
</li>
<li><strong>Unary&nbsp;</strong>operations (apply the operation separately to each element of the array)
<ul>
<li>np.abs(x)</li>
<li>np.exp(x), np.log(x), np.log2(x), np.log10(x)</li>
<li>np.sin(x), np.cos(x), np.tan(x), np.arctan(x)</li>
<li>...</li>
<p><img src="./img/n6.png" alt="" width="300" height="100" /></p>
</ul>
</li>
</ul>

In [48]:
x = np.array([[1, 2], [2, 2]])
y = np.array([[3, 4], [5, 6]])

print(f"x * y = \n{x*y}\n")
print(f"exp(x) = \n{np.exp(x)}")

x * y = 
[[ 3  8]
 [10 12]]

exp(x) = 
[[2.71828183 7.3890561 ]
 [7.3890561  7.3890561 ]]


<p><strong>Aggregate functions</strong></p>
<ul>
<li>Functions that returns a single value from an array
<ul style="list-style-type: square;">
<li>np.min(x), np.max(x) <em>or x.min(), x.max()</em></li>
<li>np.mean(x), np.std(x) <em>or x.mean(), x.std()</em></li>
<li>np.sum(x)&nbsp;<em>or x.sum()</em></li>
<li>np.argmin(x), np.argmax(x)&nbsp;<em>or x.argmin(), x.argmax()</em></li>
</ul>
</li>
<li>Aggregation functions along axes
<ul style="list-style-type: square;">
<li>Specify the operation and the axis</li>
<li>The aggregation dimension is removed from the output</li>
</ul>
</li>
</ul>

In [52]:
x = np.array([[1, 7], [2, 4]])
print(x.argmax(axis=0))
print(x.argmax(axis=1))
print(x.sum(axis=0))
print(x.sum(axis=1))

[1 0]
[1 1]
[ 3 11]
[8 6]


In [62]:
y = np.array([[[1, 2, 3], [4, 5, 6]], 
              [[7, 8, 9], [10, 11, 12]],
              [[13, 14, 15], [16, 17, 18]]])

y.min(axis=-1)

array([[ 1,  4],
       [ 7, 10],
       [13, 16]])

<p><img src="./img/n9.png" alt="" width="348" height="100" /></p>

In [64]:
y.min(axis=1)

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

<p><img src="./img/n10.png" alt="" width="348" height="100" /></p>

<p><strong>Sorting</strong></p>
<ul>
<li>The sort() methods it is possible to specify the axis along which sorting the array (-1 by default)
<ul style="list-style-type: square;">
<li>np.sort(x) - creates a sorted copy of x</li>
<li>x.sort() - sorts x inplace</li>
</ul>
</li>
<li>It is also possible to return the position of te indices of the sotred array (by default on axis -1)
<ul style="list-style-type: square;">
<li>np.argsort(x)</li>
</ul>
</li>
</ul>

In [4]:
x = np.array([[2, 1, 3], [7, 8, 9]])
np.sort(x)

array([[1, 2, 3],
       [7, 8, 9]])

<p><img src="./img/n11.png" alt="" width="348" height="100" /></p>

In [8]:
x = np.array([[2, 7, 3], [7, 2, 1]])
np.sort(x, axis=0)

array([[2, 2, 1],
       [7, 7, 3]])

<p><img src="./img/n12.png" alt="" width="348" height="100" /></p>

In [9]:
x = np.array([9,1,8,3,7,4,6,5])
np.argsort(x)

array([1, 3, 5, 7, 6, 4, 2, 0])

In [10]:
x = np.array([[2, 1, 3], [7, 8, 9]])
np.argsort(x)

array([[1, 0, 2],
       [0, 1, 2]])

<p><img src="./img/n13.png" alt="" width="348" height="100" /></p>

<p><strong>Algebraic operations</strong></p>
<p>The np.dot(x,y) returns the matrix product between the arrays passed as parameter. The resulting shape depends on the original shapes of the arguments that have to be coherent with th operation performed</p>

In [14]:
x = np.array([1, 2, 3])
y = np.array([0, 2, 1])

np.dot(x,y)

7

<p><img src="./img/n14.png" alt="" width="225" height="100" /></p>

In [15]:
x = np.array([[1, 1], [2, 2]])
y = np.array([2, 3])

np.dot(x,y)

array([ 5, 10])

<p><img src="./img/n15.png" alt="" width="250" height="100" /></p>

In [16]:
x = np.array([[1, 1], [2, 2]])
y = np.array([[2, 2], [1, 1]])

np.dot(x,y)

array([[3, 3],
       [6, 6]])

<p><img src="./img/n16.png" alt="" width="350" height="100" /></p>

### Example

## Broadcasting

<p>The concept of broadcasting is extremely useful when there is the need to perform operations between arrays with <strong>different shapes</strong></p>

<p><img src="./img/n17.png" alt="" width="500" height="100" /></p>

<ol>
<li>The shape of the array with&nbsp;<strong>fewer dimensions</strong> is&nbsp;<strong>padded&nbsp;</strong>with leading ones</li>
<li>If the shape along a dimension is 1 for one of the arrays, and &gt;1 for the other, the smaller array is&nbsp;<strong>stretched to match to other array</strong></li>
<li>If there is a dimension where both arrays have shape &gt;1 broadcasting&nbsp;<strong>cannot be performed</strong></li>
</ol>