# Numpy

## Arrays

<p>Numpy arrays are fixed-type contiguous collections with high flexibility and efficiency in indexing methods and operations. There are several data types that can be used for arrays, the most common are:</p>
<ul>
<li><em>int8, int16, int32, int64</em></li>
<li><em>uint8, uint16, uint32, uint64</em></li>
<li><em>float16, float16, float64</em></li>
<li><em>complex64, complex128</em></li>
<li><em>bool</em></li>
</ul>
<p><strong>Multidimensiona arrays</strong></p>
<p>Each array is characterized by a set of&nbsp;<strong>axes&nbsp;</strong>and a&nbsp;<strong>shape</strong>. The axes of an array define its dimensions:</p>
<ul>
<li>a row vectos has 1 axis</li>
<li>a 2D matrix has 2 axes</li>
<li>a ND array has N axes</li>
</ul>
<p><img src="./img/n2.png" alt="" width="348" height="100" /></p>
<p>Axes can be numbered with negative values, the axis with index -1 is always along the <strong>row</strong>, while the last dimension added always take the lowest value (with sign) both with positive and negative indexing.</p>
<p>The <strong>shape</strong> of an array is a tuple that specifies the number of elements along each axis. a column vector is a 2D matrix.</p>
<p><img src="./img/n3.png" alt="" width="348" height="100" /></p>
<p><img src="./img/n4.png" alt="" width="348" height="100" /></p>

In [5]:
import numpy as np

matrix = [[1, 2, 3], 
          [4, 5, 6], 
          [7, 8, 9]]

np.array(matrix, dtype=np.uint8)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=uint8)

In [15]:
null_matrix = np.zeros((2, 3), dtype=np.int8)
id_matrix = np.ones((2, 3), dtype=np.int8)
full_matrix = np.full((3, 3), 10, dtype=np.int8)

print(null_matrix, end='\n\n')
print(id_matrix, end='\n\n')
print(full_matrix, end='\n\n')

[[0 0 0]
 [0 0 0]]

[[1 1 1]
 [1 1 1]]

[[10 10 10]
 [10 10 10]
 [10 10 10]]



In [22]:
#10 sample in range 0-1
linear = np.linspace(0, 1, 10)

#Sequence 10-20 with step 2
step_2 = np.arange(10, 21, 2)

#Random (2,3) matrix with normal distribution µ=5 std=2
gauss_matrix = np.random.normal(5, 2, (2,3)) 

#Random (3,4) matrix with uniform distribution on [0,1]
uniform_matrix = np.random.random((3, 4))

print(linear, end='\n\n')
print(step_2, end='\n\n')
print(gauss_matrix, end='\n\n')
print(uniform_matrix, end='\n\n')

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

[10 12 14 16 18 20]

[[6.85297424 3.45181087 4.60646984]
 [2.79465194 6.17277103 4.63421926]]

[[0.30015284 0.24675824 0.65499347 0.65107258]
 [0.91260191 0.19759293 0.35468297 0.46651739]
 [0.36234707 0.69808161 0.75283637 0.19247025]]



In [26]:
x = np.array([[2, 3, 4], [8, 6, 7]])
dimensions = x.ndim 
matrix_shape = x.shape
matrix_size = x.size

print(dimensions, matrix_shape, matrix_size)

2 (2, 3) 6


## Computation on Numpy

<p><strong>Universal Functions (element-wise)</strong></p>
<ul>
<li><strong>Binary</strong> operations with arrays of the <strong>same shape</strong><br />
<ul>
<li>sum &amp; subtraction (+ -)</li>
<li>multiplication &amp; division (* /)</li>
<li>modulus (%)</li>
<li>floor division (//)</li>
<li>exponentiation (**)</li>
<p><img src="./img/n5.png" alt="" width="348" height="100" /></p>
</ul>
</li>
<li><strong>Unary&nbsp;</strong>operations (apply the operation separately to each element of the array)
<ul>
<li>np.abs(x)</li>
<li>np.exp(x), np.log(x), np.log2(x), np.log10(x)</li>
<li>np.sin(x), np.cos(x), np.tan(x), np.arctan(x)</li>
<li>...</li>
<p><img src="./img/n6.png" alt="" width="348" height="100" /></p>
</ul>
</li>
</ul>

In [48]:
x = np.array([[1, 2], [2, 2]])
y = np.array([[3, 4], [5, 6]])

print(f"x * y = \n{x*y}\n")
print(f"exp(x) = \n{np.exp(x)}")

x * y = 
[[ 3  8]
 [10 12]]

exp(x) = 
[[2.71828183 7.3890561 ]
 [7.3890561  7.3890561 ]]
