In [5]:
import numpy as np

arr = [[[1, 2, 3], [4, 5, 6]],
       [[7, 8 ,9], [10, 11, 12]],
       [[10, 11, 12], [13, 14, 15]]]

num_arr = np.array(arr, dtype=np.uint8)
num_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[10, 11, 12],
        [13, 14, 15]]], dtype=uint8)

In [11]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = x[0,1]
y

2

In [12]:
y = x[1:,1:] #select 5,6 and 8,9
y

array([[5, 6],
       [8, 9]])

In [18]:
y = x[0:3:2,1:] # select 2,3 and 8,9
y

array([[2, 3],
       [8, 9]])